### ISSUE TITLE
No reset function

### ISSUE THREAD

**Issue by dmizutani** [sstaub/Timer#1]
I'm writing a program for a thermostat timer but there doesn't seem to be a way to reset the timer,. The stop and pause function do the same thing.

**Comment by sstaub** [comment]
stop() and pause() have different states of the timer

**Comment by dmizutani** [comment]
How do I reset the timer though?

**Comment by sstaub** [comment]
first stop() the timer, than start() again

**Comment by sstaub** [comment]
I think start() without stopping should do the same

**Comment by dmizutani** [comment]
yes, I just do start() and stop() right after and the timer reads 0 without continuing
